### ISSUE TITLE
On ECONNRESET, `assert()` calls undefined `res.status` which throws an error

### ISSUE THREAD

**Issue by kadishmal** [visionmedia/supertest#258] opened 2015-07-14 09:28 UTC
When for some reason the remote server fails and the connection is reset, `supertest` cannot handle the error properly which is why the following error is thrown:

	|"TypeError: Cannot read property 'status' of undefined",
	|"    at Test.assert (/webapp/node_modules/supertest/lib/test.js:203:12)",
	|"    at assert (/webapp/node_modules/supertest/lib/test.js:132:12)",
	|"    at /webapp/node_modules/supertest/lib/test.js:129:5",
	|"    at Test.Request.callback (/webapp/node_modules/superagent/lib/node/index.js:781:12)",
	|"    at ClientRequest.<anonymous> (/webapp/node_modules/superagent/lib/node/index.js:736:10)",
	|"    at ClientRequest.emit (events.js:95:17)",
	|"    at Socket.socketOnEnd [as onend] (http.js:1569:9)",
	|"    at Socket.g (events.js:180:16)",
	|"    at Socket.emit (events.js:117:20)",
	|"    at _stream_readable.js:944:16",
	|"    at process._tickCallback (node.js:448:13)"

There is this code on line 202 in `supertest/lib/test.js`:

    if (status) {
      if (res.status !== status) {
        var a = http.STATUS_CODES[status];
        var b = http.STATUS_CODES[res.status];
        return fn(new Error('expected ' + status + ' "' + a + '", got ' + res.status + ' "' + b + '"'), res);
      }
  
      // remove expected superagent error
      if (resError && resError instanceof Error && resError.status === status) {
        resError = null;
      }
    }

On the line 203, which says `if (res.status !== status) {`, `res` is undefined. Because `resError = { [Error: socket hang up] code: 'ECONNRESET', response: undefined }`.

**Comment by RomanSchmidtAppinio** [comment] 2015-07-16 10:36
Same here. During a stress test mongoose connection limit is reached and node is sending an empty result. So i get same exception.

My temporary Solution: 

Test.prototype.assert = function(resError, res, fn){
  if(!res) {
    res = {
        status: 'FOOO'
    };
  }

**Comment by mikelax** [comment] 2015-07-22 20:42
This is a duplicate of #237. There is PR #258 to address this.

**Closed by mikelax** 2015-07-22 20:42 UTC

**Comment by kadishmal** [comment] 2015-10-19 09:13
#260 doesn't fix this issue. Need to reopen.

**Comment by mleanos** [comment] 2015-10-29 04:36
I'm having this issue as well on Windows 7. I've described my experiences with this issue here https://github.com/visionmedia/supertest/issues/230

**Comment by varunj90** [comment] 2015-11-23 16:40
@kadishmal , @mleanos  - any resolution to this?

https://github.com/visionmedia/supertest/issues/298

if you could help me with 298 . thanks !

**Comment by kadishmal** [comment] 2015-11-24 03:02
No, this particular issue is still present. `res.status` is not handled properly because `res` is undefined.

**Comment by varunj90** [comment] 2015-11-24 14:47
@kadishmal  - thanks for the update. Do you know ETA for this fix; or know if supertest is working towards a fix?

**Comment by varunj90** [comment] 2015-11-24 15:49
@mikelax  - Do you know ETA for this fix; or know if supertest is working towards a fix?

**Comment by aides** [comment] 2016-08-29 15:58
It's quite an old thread and it is closed, but I still encounter this issue. It is reproduced on **Windows** only and when I send a PUT with binary content with **content-type** set to a different value. 
After googling this is still the most relevant place, so maybe someone knows how to address this problem?
