### ISSUE TITLE
expect(!2xx) throws exception

### ISSUE THREAD

**Issue by midrissi** [visionmedia/supertest#556] opened 2019-03-09 23:35 UTC
I have migrated to the latest version of supertest (4.0.0), but all my tests that expect a status code different to 2xx fails.

Example:

```js
const request = require('supertest');
const express = require('express');

const app = express();

app.get('/user', function (req, res) {
  res.status(404).end();
});

(async () => {
  await request(app)
    .get('/user')
    .expect(404)
    .send({ hello: 'hi' })
})();
```

Will throw an `Error: Not Found` exception.

**Comment by midrissi** [comment] 2019-03-10 00:09
A simple test case:

```js

it('should assert using promises', function (done) {
  const app = express();

  app.get('/', function (req, res) {
    res.status(400).end();
  });

  request(app)
    .get('/')
    .expect(400)
    .then(done)
    .catch(done);
});
```

**Comment by Jackie-Tan** [comment] 2019-03-10 04:03
I have similar issue too. 
My code: 
```node.js
const request = require('supertest');
const express = require('express');

const app = express();

app.get('/user', function (req, res) {
  res.status(400).send();
});

test('Should pass this test with status 400', async () => {
	await request(app).get('/user').expect(400)
})
```
Expect the test to pass, but instead:

```
 FAIL  tests/testing.test.js
  ● Should pass this test with status 400

    Bad Request

      at Test.Object.<anonymous>.Request.callback (node_modules/superagent/lib/node/index.js:804:15)
      at IncomingMessage.parser (node_modules/superagent/lib/node/index.js:1036:18)
```

**Comment by kevinbosman** [comment] 2019-03-10 13:30
This is the same issue as #534, which was caused by upgrading superagent to v4.1.0. This previous issue was resolved at the time by downgrading superagent to v3.8.3.

superagent has again been upgraded without a proper fix in place.

**Comment by ahce** [comment] 2019-03-10 14:33
async and promises are broken
Only works this:
```
request(app)
    .get('/')
    .expect(400)
    .end(done);
```

**Comment by bonesoul** [comment] 2019-03-11 09:15
same here.

**Comment by rimiti** [comment] 2019-03-11 09:27
@gjohnson Do you have some time for fixing that? 🙏

**Comment by posquit0** [comment] 2019-03-11 09:57
same here

**Comment by fega** [comment] 2019-03-11 12:20
Same here, I'm not sure if this change was intented, but a !2XX response shouldn't trigger a failure

**Comment by jbinto** [comment] 2019-03-11 16:48
Worth following upstream: https://github.com/visionmedia/superagent/issues/1466

**Comment by gjohnson** [comment] 2019-03-13 04:29
@rimiti looking at this right now - these reports are much clearer @midrissi.

**Comment by jsstrn** [comment] 2019-03-14 10:53
Thanks for reporting the issue. While we are waiting for a fix, we can use this technique to resolve it:

```
it("fails as there is no such book", () => {
  return request(app)
    .get("/")
    .catch(res => {
      expect(res.status).toBe(400);
    });
});
```

Or, with async/await:

```
it("fails as there is no such book", async () => {
  await request(app)
    .get("/")
    .catch(res => {
      expect(res.status).toBe(400);
    });
});
```

**Comment by rimiti** [comment] 2019-03-15 12:50
#558 merged, I close this issue. 

Thank you 🙏

**Closed by rimiti** 2019-03-15 12:50 UTC
Labels: needs-investigation
