### ISSUE TITLE
From 3.x to 4.x, is there a new way to use request() ?

### ISSUE THREAD

**Issue by converge** [visionmedia/supertest#557] opened 2019-03-11 21:10 UTC
if I call my API in this way using Supertest 4.x:

```js
return res.status(401).send()
```
and try to assert it in this way:
```js
response = await request(app).post('/admin').send( { data_here } )
expect(response.status).toBe(401);
```

Supertest returns ```Unauthorized``` and not status code 401 as I'm expecting.

If I do the same thing using Supertest 3.x , it returns the status code I'm expecting to test it.

Is there a new way to do it on version 4.x ?

**Comment by blacksonic** [comment] 2019-03-12 12:54
We used to set the expected status code, like 401, but that no longer returns the response, it throws the error instead.
Seems like a breaking change without documentation.

**Comment by Christilut** [comment] 2019-03-12 13:07
Same here, used this in 3.x:
```js
  await request(app)
    .post('/system/invoice/generate')
    .set('content-type', 'application/json')
    .set('Authorization', 'invalidtoken')
    .send()
    .expect(httpStatus.UNAUTHORIZED)
```

Short migration guide would be nice

**Comment by bajtos** [comment] 2019-03-12 13:28
This may be a regression - see https://github.com/visionmedia/superagent/issues/1466

**Comment by bonesoul** [comment] 2019-03-12 13:54
same and has been reported yesterday but still no fixes.

**Comment by bonesoul** [comment] 2019-03-12 13:55
same and has been reported yesterday but still no fixes.

**Comment by bonesoul** [comment] 2019-03-12 13:55
same and has been reported yesterday but still no fixes.

**Comment by akirilyuk** [comment] 2019-03-12 15:12
Guy, you don't really test? The exact same issue happened already with v3.4.0.

https://github.com/visionmedia/supertest/issues/534

Can you please create a meaningful test, so a new version wont break anything? Or mark this as a breaking change...

**Comment by akirilyuk** [comment] 2019-03-12 15:12
Don't you have any tests which cover these cases? I mean there was already something similar:

https://github.com/visionmedia/supertest/issues/534

**Comment by SMenigat** [comment] 2019-03-13 14:56
> Don't you have any tests which cover these cases? I mean there was already something similar:
> 
> #534

Feel free to open an PR and add those tests 👍

**Comment by gjohnson** [comment] 2019-03-13 15:18
I’ve started adding a few tests, the problem is all the tests use callbacks only, so the regression was overlooked, again (sorry!).

**Comment by SMenigat** [comment] 2019-03-13 15:34
Just to be clear, my comment was in @akirilyuk s direction.

**Comment by akirilyuk** [comment] 2019-03-13 15:49
@SMenigat should not the person who created the fix also add the tests which verifies the error wont happen again? Also should it not be the maintainers job to have meaningful tests for their own product?

**Comment by bonesoul** [comment] 2019-03-14 07:58
+1 with @akirilyuk

**Comment by rimiti** [comment] 2019-03-15 12:49
#558 merged, I close this issue. 

Thank you 🙏

**Closed by rimiti** 2019-03-15 12:49 UTC
Labels: needs-investigation
